FROM node:16

# Install PM2 globally
RUN npm install -g pm2

WORKDIR /usr/src/app

COPY package*.json ./


COPY . .

RUN npm install
RUN npm run build-tsc

EXPOSE 8081

# Start the app with PM2
CMD ["node", "dist/index.js"]